version: '3.3'
services:
  php-nginx:
    image: 'nginx-php:latest'
    container_name: nginx-php-container
    volumes:
      - './pages/dashboard:/var/www/html'
      - './conf/nginx.conf:/etc/nginx/nginx.conf'
#     - './docker/php.ini:/etc/php.ini'
    ports:
      - '8000:80'
  mysql:
    image: 'hypriot/rpi-mysql:latest'
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'scrapping'
      MYSQL_PASSWORD: 'scrapping'
      MYSQL_ROOT_PASSWORD: 'scrapping'
      MYSQL_USER: 'scrapping'
    volumes:
    - './conf/docker-mysql.cnf:/etc/mysql/conf.d/docker-mysql.cnf:ro'
    - './mysql/data:/var/lib/mysql'
  php-nginx-api:
    image: 'nginx-php:latest'
    container_name: nginx-php-container-api
    volumes:
      - './pages/symfony-rest-api:/var/www/html'
      - './conf/nginx.conf:/etc/nginx/nginx.conf'
#     - './docker/php.ini:/etc/php.ini'
    ports:
    - '8080:80'
   
 
